var appStrings = {
  "Welcome back! Login": "Welcome back! Login",
  "Email or username": "Email or username",
  'Please enter your email': 'Please enter your email',
  "Email": "Email",
  "Password": "Password",
  'Please enter your password': 'Please enter your password',
  'Enter password': 'Enter password',
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  'Do not have an account?': 'Do not have an account?',
  'Register': 'Register',
  "Reset password": "Reset password",
  "Enter the email you used to creat account and we will send instruction for restting password":
      "Enter the email you used to creat account and we will send instruction for restting password",
  "Enter Email": "Enter Email",
  "Send Instructions": "Send Instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  'Enter the 4 digit code we sent to to your email in order to reset password':
      'Enter the 4 digit code we sent to to your email in order to reset password',
  'Did not receive?': 'Did not receive?',
  'Send again': 'Send again',
  "Enter new password": "Enter new password",
  "Your new password should be different from previously used password":
      "Your new password should be different from previously used password",
  'New password': 'New password',
  "Repeat new password": "Repeat new password",
  'Please retype your password': 'Please retype your password',
  'Retype new password': 'Retype new password',
  "Change password": "Change password",
  "Choose country": "Choose country",
  "Choose states": "Choose states",
  "Choose area": "Choose area",
  'Please enter your full name': 'Please enter your full name',
  "Full name": "Full name",
  "Enter your full name": "Enter your full name",
  "Username": "Username",
  'Please enter your username': 'Please enter your username',
  "Enter your username": "Enter your username",
  "Enter your email": "Enter your email",
  'Enter the 4 digit code we sent to to your email in order verify your email':
      'Enter the 4 digit code we sent to to your email in order verify your email',
  "Phone": "Phone",
  "Confirm Password": "Confirm Password",
  'Retype password': 'Retype password',
  'Have an account?': 'Have an account?',
  'Sign in': 'Sign in',
  'Phone Number': 'Phone Number',
  'Enter phone number': 'Enter phone number',
  "I agree with the terms and conditons":
      "I agree with the terms and conditons",
  'You must agree with the terms and conditions to register':
      'You must agree with the terms and conditions to register',
  'Password did not match': 'Password did not match',
  'Password must be at least 6 characters':
      'Password must be at least 6 characters',
  'Already have an account?': 'Already have an account?',
  "See all": "See all",
  "Press again to exit": "Press again to exit",
  'Welcome!': 'Welcome!',
  'Order Pending': 'Order Pending',
  'Order Completed': 'Order Completed',
  'Total Withdraw': 'Total Withdraw',
  'Remaining Balance': 'Remaining Balance',
  'Recent Orders': 'Recent Orders',
  "Order ID": "Order ID",
  "House Cleaning Service": "House Cleaning Service",
  "Repairing Services": "Repairing Services",
  "Home Shifting Service": "Home Shifting Service",
  'Online': 'Online',
  'Date': 'Date',
  'Schedule': 'Schedule',
  'Billed': 'Billed',
  'Ordered service': 'Ordered service',
  "Service ID:": "Service ID:",
  'Buyer Details': 'Buyer Details',
  'Name': 'Name',
  'Post code': 'Post code',
  'Address': 'Address',
  'Date & Schedule': 'Date & Schedule',
  'Amount Details': 'Amount Details',
  'Package fee': 'Package fee',
  'Extra service': 'Extra service',
  'Subtotal': 'Subtotal',
  'Tax': 'Tax',
  'Total': 'Total',
  'Payment status': 'Payment status',
  'Order Status': 'Order Status',
  "No details found": "No details found",
  'Payout history': 'Payout history',
  'Withdraw': 'Withdraw',
  'Payout Request Details': 'Payout Request Details',
  'ID': 'ID',
  'Amount': 'Amount',
  'Payment Gateway': 'Payment Gateway',
  'Request Date': 'Request Date',
  'Seller Note': 'Seller Note',
  'Admin Note': 'Admin Note',
  'Status': 'Status',
  'Payout Receipt': 'Payout Receipt',
  'Request date': 'Request date',
  'View': 'View',
  "Gateway": "Gateway",
  'Please enter an amount': 'Please enter an amount',
  "Note": "Note",
  'You can make a request only if your remaining balance in a range set by the site admin. Like admin set minimum request amount':
      'You can make a request only if your remaining balance in a range set by the site admin. Like admin set minimum request amount',
  "and maximum request amount": "and maximum request amount",
  "then you can request a payment between":
      "then you can request a payment between",
  "to": "to",
  'Please enter a note': 'Please enter a note',
  "Choose Reason": "Choose Reason",
  "Short description": "Short description",
  'description': 'description',
  "Deactivate": "Deactivate",
  'Please enter a description': 'Please enter a description',
  "Enter current password": "Enter current password",
  'Enter your current password': 'Enter your current password',
  'Please wait while the profile is updating':
      'Please wait while the profile is updating',
  'Please enter post code': 'Please enter post code',
  "Enter your post code": "Enter your post code",
  "Your Address": "Your Address",
  "About": "About",
  'Save': 'Save',
  'Address field is required': 'Address field is required',
  'Phone field is required': 'Phone field is required',
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  'City': 'City',
  'Area': 'Area',
  'Country': 'Country',
  'Post Code': 'Post Code',
  'Edit Profile': 'Edit Profile',
  'Address document image': 'Address document image',
  'Choose address images': 'Choose address images',
  'NID document image': 'NID document image',
  'Choose NID images': 'Choose NID images',
  'Upload': 'Upload',
  "Account verified": "Account verified",
  "Open": "Open",
  "Close": "Close",
  'Ticket ID': 'Ticket ID',
  'Chat': 'Chat',
  "Write message": "Write message",
  'Please write a message first': 'Please write a message first',
  "Make payment status complete?": "Make payment status complete?",
  "Verify Email": "Verify Email",
  'Please enter a price': 'Please enter a price',
  'Offer price': 'Offer price',
  'Cover letter': 'Cover letter',
  'Apply': 'Apply',
  'You must enter a valid price': 'You must enter a valid price',
  "Job Request ID": "Job Request ID",
  'Attachment': 'Attachment',
  'Budget': 'Budget',
  'Deadline': 'Deadline',
  'Applied jobs': 'Applied jobs',
  'You did not apply to any job': 'You did not apply to any job',
  "Buyer budget": "Buyer budget",
  "Your offer": "Your offer",
  'New jobs': 'New jobs',
  'No new jobs found': 'No new jobs found',
  'Search': 'Search',
  "Conversations": "Conversations",
  'You do not have any active conversation':
      'You do not have any active conversation',
  'Add Additional Services': 'Add Additional Services',
  "Title": "Title",
  "Enter title": "Enter title",
  "Unit price": "Unit price",
  "Enter price": "Enter price",
  "Quantity": "Quantity",
  "Enter quantity": "Enter quantity",
  'Please fill out all fields': 'Please fill out all fields',
  'Online service': 'Online service',
  'What is Included In This Package': 'What is Included In This Package',
  "Price": "Price",
  'Please enter a title': 'Please enter a title',
  'Are you sure': 'Are you sure',
  'Cancel': 'Cancel',
  'Delete': 'Delete',
  'Benefit Of This Package': 'Benefit Of This Package',
  "Type here": "Type here",
  'Please type something first': 'Please type something first',
  'Faqs': 'Faqs',
  "Faq title": "Faq title",
  "Faq answer": "Faq answer",
  "Enter answer": "Enter answer",
  "Category": "Category",
  "Child category": "Child category",
  "Sub category": "Sub category",
  'Upload main image': 'Upload main image',
  'My services': 'My services',
  'Create': 'Create',
  "Queue": "Queue",
  "Completed": "Completed",
  "Cancelled": "Cancelled",
  'Show attributes': 'Show attributes',
  'Edit attributes': 'Edit attributes',
  'Add attributes': 'Add attributes',
  'Delete service': 'Delete service',
  'Edit service': 'Edit service',
  'Create Service': 'Create Service',
  'Is available to all cities and area': 'Is available to all cities and area',
  "Video URL": "Video URL",
  "Youtube embed code": "Youtube embed code",
  'Description': 'Description',
  'Next': 'Next',
  'You must enter a title and description':
      'You must enter a title and description',
  'Description must be at least 150 characters':
      'Description must be at least 150 characters',
  'Edit': 'Edit',
  'Edit Service': 'Edit Service',
  'Starts from': 'Starts from',
  'On/Off': 'On/Off',
  'No service found': 'No service found',
  'Service attributes': 'Service attributes',
  'Include Service Attributes': 'Include Service Attributes',
  'No include service found': 'No include service found',
  'Additional Service Attributes': 'Additional Service Attributes',
  'No additional service found': 'No additional service found',
  'Service Benefit': 'Service Benefit' 'Service Benefit',
  'No service benefit found': 'No service benefit found',
  'Ok': 'Ok',
  'Please enter a quantity': 'Please enter a quantity',
  'Add': 'Add',
  'You must enter a valid amount': 'You must enter a valid amount',
  'Quantity must be an integer value': 'Quantity must be an integer value',
  'Make payment status complete': 'Make payment status complete',
  'Decline history': 'Decline history',
  "Decline reason": "Decline reason",
  "Buyer details": "Buyer details",
  'Extras': 'Extras',
  'Request buyer to mark this order complete':
      'Request buyer to mark this order complete',
  'All Orders': 'All Orders',
  'Yes': 'Yes',
  'No': 'No',
  'Details': 'Details',
  'Deactivate account': 'Deactivate account',
  "Change Password": "Change Password",
  'Report id': 'Report id',
  'Chat admin': 'Chat admin',
  'Order id': 'Order id',
  'No Report': 'No Report',
  'Report': 'Report',
  'What went wrong': 'What went wrong',
  'Write the issue': 'Write the issue',
  'Submit Report': 'Submit Report',
  'You must write a report to submit': 'You must write a report to submit',
  'Success': 'Success',
  'Subscription renewed': 'Subscription renewed',
  'Subscription details': 'Subscription details',
  'Note: Pending connect will be added to available connect only if the payment status is completed':
      'Note: Pending connect will be added to available connect only if the payment status is completed',
  'subscription': 'subscription',
  'Type': 'Type',
  'Expire date': 'Expire date',
  'Connect details': 'Connect details',
  'Available connect': 'Available connect',
  'Pending connect': 'Pending connect',
  'Payment details': 'Payment details',
  'Payment gateway': 'Payment gateway',
  'Reniew Subscription': 'Reniew Subscription',
  'Subscriptions': 'Subscriptions',
  'Start date': 'Start date',
  'No history found': 'No history found',
  'Support ticket': 'Support ticket',
  "No ticket": "No ticket",
};
